/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaConsultancyRouteImport } from './routes/visa-consultancy'
import { Route as UmrahPackagesRouteImport } from './routes/umrah-packages'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RentACarRouteImport } from './routes/rent-a-car'
import { Route as FlightBookingRouteImport } from './routes/flight-booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const VisaConsultancyRoute = VisaConsultancyRouteImport.update({
  id: '/visa-consultancy',
  path: '/visa-consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const UmrahPackagesRoute = UmrahPackagesRouteImport.update({
  id: '/umrah-packages',
  path: '/umrah-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RentACarRoute = RentACarRouteImport.update({
  id: '/rent-a-car',
  path: '/rent-a-car',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightBookingRoute = FlightBookingRouteImport.update({
  id: '/flight-booking',
  path: '/flight-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flight-booking': typeof FlightBookingRoute
  '/rent-a-car': typeof RentACarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/umrah-packages': typeof UmrahPackagesRoute
  '/visa-consultancy': typeof VisaConsultancyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flight-booking': typeof FlightBookingRoute
  '/rent-a-car': typeof RentACarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/umrah-packages': typeof UmrahPackagesRoute
  '/visa-consultancy': typeof VisaConsultancyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flight-booking': typeof FlightBookingRoute
  '/rent-a-car': typeof RentACarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/umrah-packages': typeof UmrahPackagesRoute
  '/visa-consultancy': typeof VisaConsultancyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/flight-booking'
    | '/rent-a-car'
    | '/sitemap.xml'
    | '/umrah-packages'
    | '/visa-consultancy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/flight-booking'
    | '/rent-a-car'
    | '/sitemap.xml'
    | '/umrah-packages'
    | '/visa-consultancy'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/flight-booking'
    | '/rent-a-car'
    | '/sitemap.xml'
    | '/umrah-packages'
    | '/visa-consultancy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FlightBookingRoute: typeof FlightBookingRoute
  RentACarRoute: typeof RentACarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UmrahPackagesRoute: typeof UmrahPackagesRoute
  VisaConsultancyRoute: typeof VisaConsultancyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa-consultancy': {
      id: '/visa-consultancy'
      path: '/visa-consultancy'
      fullPath: '/visa-consultancy'
      preLoaderRoute: typeof VisaConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umrah-packages': {
      id: '/umrah-packages'
      path: '/umrah-packages'
      fullPath: '/umrah-packages'
      preLoaderRoute: typeof UmrahPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-a-car': {
      id: '/rent-a-car'
      path: '/rent-a-car'
      fullPath: '/rent-a-car'
      preLoaderRoute: typeof RentACarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight-booking': {
      id: '/flight-booking'
      path: '/flight-booking'
      fullPath: '/flight-booking'
      preLoaderRoute: typeof FlightBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FlightBookingRoute: FlightBookingRoute,
  RentACarRoute: RentACarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UmrahPackagesRoute: UmrahPackagesRoute,
  VisaConsultancyRoute: VisaConsultancyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
