/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FlightBookingRouteImport } from './routes/flight-booking'
import { Route as IndexRouteImport } from './routes/index'

const FlightBookingRoute = FlightBookingRouteImport.update({
  id: '/flight-booking',
  path: '/flight-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flight-booking': typeof FlightBookingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flight-booking': typeof FlightBookingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flight-booking': typeof FlightBookingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flight-booking'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flight-booking'
  id: '__root__' | '/' | '/flight-booking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlightBookingRoute: typeof FlightBookingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/flight-booking': {
      id: '/flight-booking'
      path: '/flight-booking'
      fullPath: '/flight-booking'
      preLoaderRoute: typeof FlightBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlightBookingRoute: FlightBookingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
